### ISSUE TITLE
boot loop with latest nightly

### ISSUE THREAD

**Issue by overlander** [AsteroidOS/meta-lenok-hybris#5]
won't boot when running `fastboot boot zImage-dtb-lenok.fastboot`
bootloops if flashed
watch is running android wear build NXH19X wear 2.0.0.153815175 and using twrp-3.0.0-0-lenok+squashfs 
This is my first attempt running it so i don't know if a prior version worked.

**Comment by FlorentRevest** [comment]
Where did you push your rootfs ? Have you followed the instructions at the bottom of https://asteroidos.org/wiki/building-asteroidos/?

**Comment by overlander** [comment]
That was the problem , i was following the guide on xda. It had the rootfs as /sdcard/linux/rootfs.ext4
