### ISSUE TITLE
Alarm doesn't vibrate

### ISSUE THREAD

**Issue by GeckoEidechse** [AsteroidOS/meta-lenok-hybris#6]
The issue is the exact same as described [here for wren](https://github.com/AsteroidOS/meta-wren-hybris/issues/3)

The watch does vibrate when disabling and re-enabling vibration in the quicksettings.

Playing the alarm over ssh with `ngf-client "play alarm"` does not work:

```
root@lenok:ceres# ngf-client "play alarm"
simple ngf client
> PLAY (event=alarm, event_id=1)
> 
Playing (event_id=1)
> 
Failed (event_id=1)
```

The relevant log of `journalctl -u user@1000 --no-pager` is in [this paste here](https://ghostbin.com/paste/sa9gj)

**Comment by FlorentRevest** [comment]
Thanks for reporting. Unfortunately I can not reproduce this bug with the watches I have so it might need the help of the device's maintainers.

**Comment by GeckoEidechse** [comment]
Let's hope @atx can get to the bottom of this. If there's anything I can help you with regarding this issue, feel free to let me know.

**Comment by GeckoEidechse** [comment]
Confirming that vibrate now works when the alarm goes off using the nighlty with time stamp `27-Feb-2020 22:08` from https://release.asteroidos.org/nightlies/lenok/
