### ISSUE TITLE
Device porting status: WLAN

### ISSUE THREAD

**Issue by LittleFox94** [AsteroidOS/meta-lenok-hybris#9]
After configuring wpa_supplicant by hand (modifying the systemd unit to load the config and select the interface and adding a network to the config) WLAN works fine

And since there isn't any use for WLAN in AsteroidOS yet, this should be enough to mark it as working

**Comment by LittleFox94** [comment]
Oh and rfkill is softblocking the phy and the interface

**Comment by FlorentRevest** [comment]
Thanks! This is indeed all we take into account when considering WLAN support :)
